### PR TITLE
fix: fix concurrency bugs causing panics and race conditions in `internal/syncutil`

### LINKED ISSUE #908: Flaky unit test: `TestCopyGraph_WithOptions/MountFrom_error`
The unit test `TestCopyGraph_WithOptions/MountFrom_error` in `copy_test.go` has been flaky in recent builds.
Here is an instance: https://github.com/oras-project/oras-go/actions/runs/13639868900/job/38127074239?pr=906

> === RUN   TestCopyGraph_WithOptions/MountFrom_error
>     copy_test.go:1810: count(Exists()) = 3, want 2
>     copy_test.go:1819: count(MountFrom()) = 2, want 1
> === RUN   TestCopyGraph_WithOptions/MountFrom_OnMounted_error
> --- FAIL: TestCopyGraph_WithOptions (0.01s)
>     --- PASS: TestCopyGraph_WithOptions/SkipNode (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_mounted (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_copied (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_mounted_second_try (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_copied_dst_not_a_Mounter (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_empty_sourceRepositories (0.00s)
>     --- FAIL: TestCopyGraph_WithOptions/MountFrom_error (0.00s)
>     --- PASS: TestCopyGraph_WithOptions/MountFrom_OnMounted_error (0.00s)

https://github.com/oras-project/oras-go/blob/f3f718b3c423848c46b492669c7c433fb463b3fa/copy_test.go#L1792-L1821

### LINKED ISSUE #916: Incorrect use of `atomic.Value` in the `syncutil.Go` utility function causes panic
While using ORAS-Go to push a layout with some slightly-incorrect manifest contents I encountered this panic:

```
panic: sync/atomic: compare and swap of inconsistently typed value into Value

goroutine 83 [running]:
sync/atomic.(*Value).CompareAndSwap(0xc00034a700, {0x0, 0x0}, {0x99fe80, 0xc0004a2660})
        sync/atomic/value.go:174 +0x150
oras.land/oras-go/v2/internal/syncutil.Go[...].func1.func2()
        oras.land/oras-go/v2@v2.5.1-0.20250221033735-cb6d75be7dd4/internal/syncutil/limit.go:86 +0xe6
golang.org/x/sync/errgroup.(*Group).Go.func1()
        golang.org/x/sync@v0.11.0/errgroup/errgroup.go:78 +0x50
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 46
        golang.org/x/sync@v0.11.0/errgroup/errgroup.go:75 +0x93
```

Unfortunately I can't share with you the incorrect content since it was just throwaway stuff in a job where I didn't preserve the input artifacts, but I found the relevant code here:

https://github.com/oras-project/oras-go/blob/853e0125ccad32ff691e4ed70e156c7619021bfd/internal/syncutil/limit.go#L73-L92

I think the `egErr.CompareAndSwap` call on line 86 is incorrect, because `err` here has an interface type (`error`) and so whichever concrete error type is stored there first freezes the type expected for all future calls, per the [`Value.CompareAndSwap`](https://pkg.go.dev/sync/atomic#Value.CompareAndSwap) documentation:

> All calls to CompareAndSwap for a given Value must use values of the same concrete type. CompareAndSwap of an inconsistent type panics, as does CompareAndSwap(old, nil).

If `egErr.CompareAndSwap` gets subsequently called again with a different concrete error type from one of the other goroutines then I expect that this would generate the panic I observed.

I think one potential way to make this more robust would be for this function to declare a local struct type to act as the consistent concrete type for `egErr`, with the dynamically-typed `error` inside it:

```go
type WrappedError struct {
    err error
}
# ...

egErr.CompareAndSwap(nil, WrappedErr{err})
```

Then when loading the error again:

```go
if egErrWrap, ok := egErr.Load().(WrappedError) ok && egErrWrap.err != nil {
	return egErrWrap.err
}
```

The concrete type in `egErr` would therefore always be exactly `WrappedError`, and so this panic would then be impossible.

Again I'm sorry I can't offer a specific reproduction case for this, but I hope the above is useful. I'm not blocked by this because I've now corrected my manifest content so that it doesn't cause these errors.

### PR DESCRIPTION
**Pull request by Wwwsylvia**
1. Remove the use of `atomic.Value`
2. Cancel all go-routines before releasing semaphore permits
3. Wait for schedule go-routines to release the semaphore permits before returning
4. Add unit tests

Fixes #916, fixes #908

### CODE REVIEW

**Comment by Wwwsylvia** [comment]
Mmmm the missing lines would be tricky to cover

File: internal/syncutil/limit.go [hunk 1]
```diff
@@ -68,27 +68,57 @@ type GoFunc[T any] func(ctx context.Context, region *LimitedRegion, t T) error
...
-			return err
+			once.Do(func() {
+				// record the first error occurred
+				firstErr = err
+			})
+			// when an error occurs, cancel other tasks
+			cancel()
+			// continue loop instead of returning to allow already scheduled
+			// goroutines to finish their deferred region.End() calls
+			continue
```
Comment (shizhMSFT) [inline internal/syncutil/limit.go:89]: Why don't we just `break`?

**Review by shizhMSFT — COMMENTED** [review]
For the code coverage, let's discuss offline.

File: internal/syncutil/limit.go (hunk 1 above)
Comment (Wwwsylvia) [reply internal/syncutil/limit.go:89]: Oh good catch! We should break

**Review by shizhMSFT — APPROVED** [review]
LGTM
