### PR TITLE
fix(file.Store): fix race condition on restoring the same named content

### LINKED ISSUE #730: `file.Store` has race conditions on restoring the same named content
`file.Store` has race conditions on restoring the same named content, causing testing failures.

Output of failed test https://github.com/oras-project/oras-go/actions/runs/8358181822/job/22878904404:
```
=== RUN   TestStore_Predecessors
    file_test.go:2400: failed to push test content to src: 10: failed to restore duplicated file: "0c55e531aef3d9c23acecbf74a9ea864e6bdb0ec84b12a9cddfdbb26152d823c.blob": application/vnd.oci.image.index.v1+json: 0c55e531aef3d9c23acecbf74a9ea864e6bdb0ec84b12a9cddfdbb26152d823c.blob: duplicate name
```

### PR DESCRIPTION
**Pull request by shizhMSFT**
Fix #730

### CODE REVIEW

File: content/file/file_test.go [hunk 1]
```diff
@@ -1613,6 +1614,146 @@ func TestStore_File_Push_RestoreDuplicates_NotFound(t *testing.T) {
...
+	ctx := context.Background()
+
+	// push blob as unnamed
+	if err := fallbackMock.Push(ctx, blobDesc, bytes.NewReader(content)); err != nil {
+		t.Fatal("Store.Push() error =", err)
+	}
+	// push manifest
+	fallbackMock.OnFetch = func(ctx context.Context, desc ocispec.Descriptor) error {
+		if desc.Digest == blobDesc.Digest {
+			// push blob2 before being restored by manifest put
```
Comment (Wwwsylvia) [inline content/file/file_test.go:1681]: Where is blob2?

Comment (shizhMSFT) [reply content/file/file_test.go]: updated comment

**Review by Wwwsylvia — APPROVED** [review]
LGTM
