### PR TITLE
fix: add missing operation to fs path error

### LINKED ISSUE #640: improve the returned error of `oci.NewFromTar` when the passed-in path is not a tarfile
[oci.NewFromTar](https://pkg.go.dev/oras.land/oras-go/v2/content/oci#NewFromTar) can be used to create a new read-only OCI store from a tarfile path. If the passed-in path doesn't point to a tarfile, currently(v2.3.1) below errors will be returned:
- If the length of the file is zero, a `failed to open OCI layout file:  oci-layout: file does not exist` error will be returned
- If the length of the file is not zero, an [io.ErrUnexpectedEOF](https://pkg.go.dev/io#ErrUnexpectedEOF) will be returned

As a user of oras-go SDK, I would like this function to return a unified and exported error type. Also, the error should indicate that the passed-in path doesn't point to an expected tarfile.

### PR DESCRIPTION
**Pull request by qweeah**
When opening a folder as OCI image layout and there is no `oci-layout` file exists, the error would be

> failed to open OCI layout file:  oci-layout: file does not exist

There is a duplicated space in the error string, because the `Op` field is missing in the returned `fs.PathError`. With fix in this PR, the return error would be
> failed to open OCI layout file: open oci-layout: file does not exist

Fixes #640

### CODE REVIEW

File: internal/fs/tarfs/tarfs.go [hunk 1]
```diff
@@ -108,11 +108,11 @@ func (tfs *TarFS) Stat(name string) (fs.FileInfo, error) {
 // getEntry returns the named entry.
 func (tfs *TarFS) getEntry(name string) (*entry, error) {
 	if !fs.ValidPath(name) {
-		return nil, &fs.PathError{Path: name, Err: fs.ErrInvalid}
+		return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrInvalid}
 	}
 	entry, ok := tfs.entries[name]
 	if !ok {
-		return nil, &fs.PathError{Path: name, Err: fs.ErrNotExist}
+		return nil, &fs.PathError{Op: "open", Path: name, Err: fs.ErrNotExist}
```
Comment (Wwwsylvia) [inline internal/fs/tarfs/tarfs.go:115]: Looks like we should define a constant for "open".

Comment (qweeah) [reply internal/fs/tarfs/tarfs.go:115]: I don't know, just check `os` package and seems they doesn't add a const
https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/os/file_windows.go

Comment (shizhMSFT) [inline internal/fs/tarfs/tarfs.go:115]: `Stat` also invoke `getEntry`. We should distinguish them.

Comment (qweeah) [reply internal/fs/tarfs/tarfs.go]: Add operation as input of the getEntry method.

**Review by Wwwsylvia — APPROVED** [review]
LGTM

File: internal/fs/tarfs/tarfs.go (hunk 1 above)
Comment (Wwwsylvia) [reply internal/fs/tarfs/tarfs.go]: Nevermind, the comment became invalid now.

**Review by shizhMSFT — APPROVED** [review]
LGTM
