### PR TITLE
fix!: use absolute path for OCI root

### LINKED ISSUE #404: Bug: OCI store and File store should record an absolute path instead of a relative path for root

### PR DESCRIPTION
**Pull request by Wwwsylvia**
Fixes: #404 
BREAKING CHANGE: `oci.NewStorage()` now returns an error

### CODE REVIEW

File: content/oci/oci.go [hunk 1]
```diff
@@ -70,16 +70,25 @@ func New(root string) (*Store, error) {
 
 // NewWithContext creates a new OCI store.
 func NewWithContext(ctx context.Context, root string) (*Store, error) {
+	rootAbs, err := filepath.Abs(root)
+	if err != nil {
+		return nil, fmt.Errorf("failed to resolve absolute path for %s: %w", root, err)
+	}
```
Comment (shizhMSFT) [inline content/oci/oci.go:76]: This check is unnecessary since `NewStorage()` has already done the check.

Comment (Wwwsylvia) [reply content/oci/oci.go:76]: This is still needed because `indexPath` relies on the root path. See line 85 and line 91.

**Review by shizhMSFT — APPROVED** [review]
LGTM
