### PR TITLE
fix: check content-type when using referrers API

### LINKED ISSUE #633: Repository.Referrers does not properly detect the absence of the referrers API for registry.k8s.io
To reproduce

```shell
$ oras discover registry.k8s.io/sig-storage/csi-resizer:v1.8.0
Error: GET "https://accounts.google.com/v3/signin/identifier REDACTED": failed to decode response: invalid character '<' looking for beginning of value
```

The issue does not seem to be with in the `oras` CLI tool but rather the detection logic within the Repository's Referrers method to determine when a registry supports the referrers API or not.  In the above example, `registry.k8s.io` was erroneously determined to implement the referrers API.  In reality the response was a 307 that was followed to a login page for a user that was HTML and page returned a 200 so `oras-go` thinks that it supports the referrers API.  Then when the referrers API is used, it is obvious that the JSON parser is trying to parse HTML.  Not good.

So we need better detection logic for the referrers API.  Having the request (made in pingReferrers) respond with a 200 is necessary but not sufficient in most cases.   **We could check that the content type in the response is actually an OCI index.**  It looks like there are lots of places withing `oras-go` where the Content-Type of the response is not checked to be a set of acceptable values before parsing the body.  This is generally considered bad practice.

### PR DESCRIPTION
**Pull request by ktarplee**
When accessing the referrer's API, this adds a check to make sure the content-type is an OCI index.

Also fixes the tests to properly set the content-type header in the response.

Closes #633

### CODE REVIEW

File: registry/remote/repository.go [hunk 1]
```diff
@@ -548,6 +548,11 @@ func (r *Repository) referrersPageByAPI(ctx context.Context, artifactType string
 		return "", errutil.ParseErrorResponse(resp)
 	}
 
+	if resp.Header.Get("Content-Type") != ocispec.MediaTypeImageIndex {
+		resp.StatusCode = http.StatusNotFound
```
Comment (ktarplee) [inline registry/remote/repository.go:552]: I'm not sure this is the correct way to return this error.

File: registry/remote/repository.go [hunk 2]
```diff
@@ -548,6 +548,11 @@ func (r *Repository) referrersPageByAPI(ctx context.Context, artifactType string
...
+		return "", errutil.ParseErrorResponse(resp)
```
Comment (shizhMSFT) [inline registry/remote/repository.go:553]: We should modify the response status code. Instead, we can do something like
```go
err := errutil.ParseErrorResponse(resp)
return "", fmt.Errorf("unknown content returned, expecting image index: %w", err)
```
You may improve the error message :P

File: registry/remote/repository_test.go [hunk 3]
```diff
@@ -7082,6 +7091,7 @@ func TestRepository_pingReferrers(t *testing.T) {
 		switch {
 		case r.Method == http.MethodGet && r.URL.Path == "/v2/test/referrers/"+zeroDigest:
 			count++
+			w.Header().Set("Content-Type", ocispec.MediaTypeImageIndex)
```
Comment (Wwwsylvia) [inline registry/remote/repository_test.go:7094]: Can we have another test case for `pingReferrers` and `Referrers`, where `200` is returned with an unexpected content type?

Comment (ktarplee) [reply registry/remote/repository_test.go]: I added two tests since there are two places in the code that have to check the referrer's content type.

File: registry/remote/repository.go (hunk 2 above)
Comment (ktarplee) [reply registry/remote/repository.go]: I am using `errors.Join` to return multiple errors from the function.

File: registry/remote/repository.go (hunk 1 above)
Comment (ktarplee) [reply registry/remote/repository.go]: This was handled by the discussion below.

**Comment by ktarplee** [comment]
@Wwwsylvia @shizhMSFT This is ready from my perspective.  Once you review it I can update the branch to it is a single fast-forward commit if desired.

**Comment by ktarplee** [comment]
@shizhMSFT Can we get this merged?

**Comment by Wwwsylvia** [comment]
Just back from some other work, sorry for the delay! I'm reviewing it.

File: registry/remote/repository.go [hunk 4]
```diff
@@ -544,10 +542,21 @@ func (r *Repository) referrersPageByAPI(ctx context.Context, artifactType string
 	}
 	defer resp.Body.Close()
 
-	if resp.StatusCode != http.StatusOK {
+	switch resp.StatusCode {
+	case http.StatusOK:
+	case http.StatusNotFound:
+		// A 404 returned by Referrers API indicates that Referrers API is not supported.
+		return "", errors.Join(errdef.ErrUnsupported, errutil.ParseErrorResponse(resp))
```
Comment (Wwwsylvia) [inline registry/remote/repository.go:549]: If the status code is 404 and the error code is `NAME_UNKNOWN`, it means that the repository does not exist, and the referrers API status is still unknown. For such case, we shouldn't return `ErrUnsupported`.

Comment (Wwwsylvia) [reply registry/remote/repository.go:549]: How about:

```suggestion
		if errResp := errutil.ParseErrorResponse(resp); errutil.IsErrorCode(errResp, errcode.ErrorCodeNameUnknown) {
			// The repository is not found, Referrers API status is unknown
			return "", errResp
		}
		// Referrers API is not supported.
		return "", fmt.Errorf("failed to query referrers API: %w", errdef.ErrUnsupported)
```

File: registry/remote/repository.go [hunk 5]
```diff
@@ -483,16 +483,14 @@ func (r *Repository) Referrers(ctx context.Context, desc ocispec.Descriptor, art
...
-		var errResp *errcode.ErrorResponse
-		if !errors.As(err, &errResp) || errResp.StatusCode != http.StatusNotFound {
+		if !errors.Is(err, errdef.ErrUnsupported) {
 			return err
 		}
-		if errutil.IsErrorCode(errResp, errcode.ErrorCodeNameUnknown) {
+		if errutil.IsErrorCode(err, errcode.ErrorCodeNameUnknown) {
 			// The repository is not found, no fallback.
 			return err
 		}
```
Comment (Wwwsylvia) [inline registry/remote/repository.go:492]: How about:
If we move the check for the repository not found case to `referrersByAPI`, we can do:
```go
	if err != nil {
		if errors.Is(err, errdef.ErrUnsupported) {
			// Referrers API is not supported, fallback to referrers tag schema.
			r.SetReferrersCapability(false)
			return r.referrersByTagSchema(ctx, desc, artifactType, fn)
		}
		return err
	}
```

**Comment by ktarplee** [comment]
@Wwwsylvia I liked you changes.  I tested them and it still resolves the original issue.   Let me know if there are any other changes or if you want me to squash the commits.

File: registry/remote/repository.go [hunk 6]
```diff
@@ -483,16 +483,13 @@ func (r *Repository) Referrers(ctx context.Context, desc ocispec.Descriptor, art
...
-			return err
+		if errors.Is(err, errdef.ErrUnsupported) {
+			// Referrers API is not supported, fallback to referrers tag schema.
+			r.SetReferrersCapability(false)
+			return r.referrersByTagSchema(ctx, desc, artifactType, fn)
 		}
-		// A 404 returned by Referrers API indicates that Referrers API is
-		// not supported. Fallback to referrers tag schema.
+		return err
+		// Fallback to referrers tag schema.
```
Comment (Wwwsylvia) [inline registry/remote/repository.go:492]: We need to remove line 492-494

Comment (shizhMSFT) [reply registry/remote/repository.go:492]: Agree to remove the code in a dead path.

**Comment by ktarplee** [comment]
@Wwwsylvia @shizhMSFT This is rebased and should be ready to be merged.

**Review by Wwwsylvia — APPROVED** [review]
LGTM
