### PR TITLE
fix!: `Tag()` and `TagN()` return a descriptor

### LINKED ISSUE #395: design: `Tag()` and `TagN()` should return a descriptor
[oras.Tag()](https://pkg.go.dev/oras.land/oras-go/v2#Tag) and [oras.TagN()](https://pkg.go.dev/oras.land/oras-go/v2#TagN) do not return a descriptor. Thus, there is no way to know which content is re-tagged exactly.

This is a design flaw / bug and should be fixed.

### PR DESCRIPTION
**Pull request by shizhMSFT**
Fix #395

### CODE REVIEW

File: content.go [hunk 1]
```diff
@@ -82,60 +82,43 @@ func TagN(ctx context.Context, target Target, srcReference string, dstReferences
...
-			eg.Go(func(dst string) func() error {
-				return func() error {
-					r := bytes.NewReader(contentBytes)
-					if err := refPusher.PushReference(egCtx, desc, r, dst); err != nil && !errors.Is(err, errdef.ErrAlreadyExists) {
-						return fmt.Errorf("failed to tag %s as %s: %w", srcReference, dst, err)
-					}
-					return nil
-				}
-			}(dstRef))
+		if err := tagBytesN(ctx, target, desc, contentBytes, dstReferences, TagBytesNOptions{
```
Comment (qweeah) [inline content.go:111]: Can we remove the reference fetcher and reference pusher check and always use `content.FetchBytes` and `content.tagBytesN`?

Comment (qweeah) [reply content.go:111]: Please resolve it. Looks like the proposal doesn't perform well when the Target is local, e.g. memory target.

**Review by Wwwsylvia — APPROVED** [review]
LGTM
