### PR TITLE
fix: add error detail to resolve failure

### LINKED ISSUE #389: improve the error message if failed to resolve a reference in OCI store
For now, resolving failure will only return `not found` and the context of resolving a reference and what is solved is missing.

### PR DESCRIPTION
**Pull request by qweeah**
Resolves: #389

### CODE REVIEW

File: copy.go [hunk 1]
```diff
@@ -133,8 +133,9 @@ func Copy(ctx context.Context, src ReadOnlyTarget, srcRef string, dst Target, ds
 	}
 	proxy := cas.NewProxyWithLimit(src, cas.NewMemory(), opts.MaxMetadataBytes)
 	root, err := resolveRoot(ctx, src, srcRef, proxy)
+
```
Comment (shizhMSFT) [inline copy.go:136]: remove extra empty line

**Review by shizhMSFT — APPROVED** [review]
LGTM
